config/routes.rb
Rails.application.routes.draw do 
  get 'rooms/index'
  get 'roomtypes/index'
  get 'listhotels', to: 'hotels#index'
  get 'hotels/:id',to: 'hotels#show', as: 'hotels'
  get 'addhotels',to: 'hotels#new'
  post 'addhotels',to: 'hotels#create'
  get 'hotels/:id/edit', to: 'hotels#edit',as: 'edit_hotel'
  patch 'hotels/:id/edit',to: 'hotels#update'
  delete 'hotels/:id',to: 'hotels#destroy',as: 'delete_hotel'

  get 'listroomtypes' ,to: 'roomtypes#index'
  get 'roomtypes/:id',to: 'roomtypes#show', as: 'roomtypes'
  get 'addroomtypes',to: 'roomtypes#new'
  post 'addroomtypes',to: 'roomtypes#create'
  get 'roomtypes/:id/edit', to: 'roomtypes#edit',as: 'edit_roomtype'
  patch 'roomtypes/:id/edit',to: 'roomtypes#update'
  delete 'roomtypes/:id',to: 'roomtypes#destroy',as: 'delete_roomtype'

  get 'allotroom',to: 'rooms#index'
  get 'addguestandbooking' ,to: 'bookings#new'
  get 'addbookings' ,to: 'bookings#create'
  get '/bookings/:id',to: 'bookings#show',as: 'booking'
  get 'bills/new/:booking_id',to: 'bills#new',as:'new_booking_bill'
  post 'bills' ,to: 'bills#create',as: 'create_booking_bill'
  get '/bills/:id',to: 'bills#show',as: 'bill'
  get 'genbills',to: 'bills#payment'
  get 'feedbacks',to: 'feedbacks#new'
  post 'feedbacks',to: 'feedbacks#create'
  get 'addfeedbacks',to: 'feedbacks#create'
  post 'addfeedbacks',to: 'feedbacks#create'
  get 'thankyou',to: 'static_pages#thankyou'
  root 'static_pages#home'
  get 'static_pages/home'
  get 'static_pages/help'
  get 'signup' ,to: 'users#new'

  get 'login',to: 'sessions#new'
  post 'login',to: 'sessions#create'
  delete 'logout',to: 'sessions#destroy'


  resources :users
  get 'users/:id',to: 'users#show', as: 'usersshow'
end

app/controllers/roomtypes_controller.rb
class RoomtypesController < ApplicationController
  include SessionsHelper
  def index
    @roomtypes=Roomtype.all
    if !admin? 
    @selected_hotel=Hotel.find(params[:hotel])
    end
  end

  def show
    @roomtype=Roomtype.find(params[:id])
  end

  def new
    @roomtype = Roomtype.new
  end

  def create
    @roomtype = Roomtype.new(roomtype_params)
    @roomtype.image.attach(params[:roomtype][:image]) if params[:roomtype][:image].present?
    if @roomtype.save
      flash.now[:success] = "Roomtype added to the list"
      redirect_to roomtypes_path(@roomtype.id)
    else
      render 'new'
    end
  end
  
  def edit 
    @roomtype = Roomtype.find(params[:id])
  end

  def update 
    @roomtype = Roomtype.find(params[:id])
    if @roomtype.update(roomtype_params)
      flash.now[:success] = "Roomtype is successfully updated!"
      redirect_to roomtypes_path(@roomtype.id)
    else
      render 'edit'
    end
  end

  def destroy
    @roomtype = Roomtype.find(params[:id])
    @roomtype.destroy
    flash.now[:success]= "Roomtype deleted successfully!"
    redirect_to listroomtypes_path
  end

  private
  def roomtype_params
    params.require(:roomtype).permit(:image, :description, :facilities,:hotel_id)
  end
end

app/helpers/roomtypes_helper.rb
module RoomtypesHelper
end

app/views/roomtypes/edit.html.erb
<h1 class="text-center">Edit Hotel</h1>

<div class="row">
  <div class="mx-auto col-10 col-md-8 col-lg-6">
    <%= form_for @roomtype, url: edit_roomtype_path(@roomtype),method: :patch do |f| %>
      <%= render 'shared/errors_msg' %>

      <%= f.label :image %>
      <%= f.file_field :image ,class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_field :description ,class: 'form-control'%>

      <%= f.label :facilities %>
      <%= f.text_field :facilities ,class: 'form-control'%>
      
      <%= f.label :hotel_id %>
      <%= f.number_field :hotel_id,in: 1..100 ,class: 'form-control'%>
      <br>
      <%= f.submit "Update Hotel", class: "btn btn-primary" %>
    <% end %>
  </div>
</div> 

app/views/roomtypes/index.html.erb
<header class="header">
<h1>List Of Available Roomtypes</h1>
</header>
<ul>
  <% @roomtypes.each do |roomtype|%>
    <li>
      <%= roomtype.description %>
      <% if !admin? %>
        <%= link_to "View",roomtypes_path(roomtype.id)%>
      <% end %>
      <% if admin? %>
        <%= link_to "View",roomtypes_path(roomtype.id)%>
        <%= link_to "Modify",edit_roomtype_path(roomtype.id)%>
        <%= link_to "Delete",delete_roomtype_path(roomtype.id),method: :delete, data: {confirm: "Are You Sure?" }%>
        (Hotel Id- <%=roomtype.hotel_id%>)
      <% end %>
    </li>
  <% end %>
</ul>
<% if admin? %>
  <%= link_to "Add RoomType",addroomtypes_path%>
<% end %>
<br>
<%= link_to "Back", listhotels_path%>

app/views/roomtypes/new.html.erb
<h1 class="text-center">Add Roomtype</h1>

<div class="row">
  <div class="mx-auto col-10 col-md-8 col-lg-6">
    <%= form_for @roomtype, url: addroomtypes_path do |f| %>
      <%= render 'shared/errors_msg' %>

      <%= f.label :image %>
      <%= f.file_field :image ,class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_field :description ,class: 'form-control'%>

      <%= f.label :facilities %>
      <%= f.text_field :facilities ,class: 'form-control'%>
      
      <%= f.label :hotel_id %>
      <%= f.number_field :hotel_id,in: 1..100 ,class: 'form-control'%>
      <br>
      <%= f.submit "Add Roomtype", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/roomtypes/show.html.erb
<header class="header">
<h1>Welcome to <%=@roomtype.description%> </h1>
</header>
<h2>Details are as below:</h2>
<%=image_tag @roomtype.image if @roomtype.image.attached?%>
<p>Description: <%=@roomtype.description%></p>
<p>Facilities: <%=@roomtype.facilities%></p>

<% if admin? %>
<p>Hotel Id: <%=@roomtype.hotel_id%></p>
<% end %>
<br>
<%= link_to "Back", listroomtypes_path%>
<% if !admin? %>
<%= link_to "select & Proceed", allotroom_path(@selected_hotel,roomtype: @roomtype)%>
<% end %>