config/routes.rb
Rails.application.routes.draw do 
  get 'rooms/index'
  get 'roomtypes/index'
  get 'listhotels', to: 'hotels#index'
  get 'hotels/:id',to: 'hotels#show', as: 'hotels'
  get 'addhotels',to: 'hotels#new'
  post 'addhotels',to: 'hotels#create'
  get 'hotels/:id/edit', to: 'hotels#edit',as: 'edit_hotel'
  patch 'hotels/:id/edit',to: 'hotels#update'
  delete 'hotels/:id',to: 'hotels#destroy',as: 'delete_hotel'

  get 'listroomtypes' ,to: 'roomtypes#index'
  get 'roomtypes/:id',to: 'roomtypes#show', as: 'roomtypes'
  get 'addroomtypes',to: 'roomtypes#new'
  post 'addroomtypes',to: 'roomtypes#create'
  get 'roomtypes/:id/edit', to: 'roomtypes#edit',as: 'edit_roomtype'
  patch 'roomtypes/:id/edit',to: 'roomtypes#update'
  delete 'roomtypes/:id',to: 'roomtypes#destroy',as: 'delete_roomtype'

  get 'allotroom',to: 'rooms#index'
  get 'addguestandbooking' ,to: 'bookings#new'
  get 'addbookings' ,to: 'bookings#create'
  get '/bookings/:id',to: 'bookings#show',as: 'booking'
  get 'bills/new/:booking_id',to: 'bills#new',as:'new_booking_bill'
  post 'bills' ,to: 'bills#create',as: 'create_booking_bill'
  get '/bills/:id',to: 'bills#show',as: 'bill'
  get 'genbills',to: 'bills#payment'
  get 'feedbacks',to: 'feedbacks#new'
  post 'feedbacks',to: 'feedbacks#create'
  get 'addfeedbacks',to: 'feedbacks#create'
  post 'addfeedbacks',to: 'feedbacks#create'
  get 'thankyou',to: 'static_pages#thankyou'
  root 'static_pages#home'
  get 'static_pages/home'
  get 'static_pages/help'
  get 'signup' ,to: 'users#new'

  get 'login',to: 'sessions#new'
  post 'login',to: 'sessions#create'
  delete 'logout',to: 'sessions#destroy'


  resources :users
  get 'users/:id',to: 'users#show', as: 'usersshow'
end

app/models/user.rb
class User < ApplicationRecord
    has_many :bookings
    has_secure_password
   
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
    validates :username,presence: true,uniqueness: true
    validates :password_digest, presence: true
    validates :role,presence: true
    validates :email, presence: true, length: { minimum: 10, maximum: 255 },format: { with: VALID_EMAIL_REGEX },uniqueness: { case_sensitive: false }
    validates :password, presence: true, length: { minimum: 6, maximum: 20 }

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper
  # def index
  #   @user=User.all
  # end
  
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:username, :email, :password,:password_confirmation,:role)
  end

end

app/helpers/users_helper.rb
module UsersHelper

    # Returns the Gravatar for the given user.
    def gravatar_for(user)
      gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
      gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
      image_tag(gravatar_url, alt: user.username, class: "gravatar")
    end
  end

app/views/users/index.html.erb
<h1>Hello</h1>
<%= @user.username %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1 class="text-center">Sign up</h1>

<div class="row">
  <div class="mx-auto col-10 col-md-8 col-lg-6">
    <%= form_for @user do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :username %>
      <%= f.text_field :username ,class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email ,class: 'form-control'%>

      <%= f.label :password %>
      <%= f.password_field :password ,class: 'form-control'%>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      <br>
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= stylesheet_link_tag "custom" %>
<header class="header">
<h1 class="first-h1">Welcome to the portal <%= @user.username %> </h1>
<p class="first-p">
  <% if !admin? %>
  <%= link_to "Feedback",feedbacks_path%>
  <% end %>
</p>
</header>
<%if !admin?%>
<h2 class="first-h2">You are just few clicks away to get a 5 star experience with us!</h2>
<p class="second-p">Let's get started"</p>
<h1>Let's Checkout Hotels Available for your service!</h1>
<h1><%= link_to "Click Here", listhotels_path%></h1>
<%#<li ><a href="search.html">Search Hotel By Name</a></li>%>
<%#<li><a href="select.html">Select Hotel By Id</a></li>%>
<%end%>

<%if admin?%>
<h2 class="first-h1">Manage Your site with ease:</h2>
<ul>
<h3><li><%= link_to "Hotels", listhotels_path%></li></h3>
<h3><li><%= link_to "Roomtypes", listroomtypes_path%></li></h3>
<h3><li><%= link_to "Rooms", listhotels_path%></li></h3>
</ul>
<% end %>