config/routes.rb
Rails.application.routes.draw do 
  get 'rooms/index'
  get 'roomtypes/index'
  get 'listhotels', to: 'hotels#index'
  get 'hotels/:id',to: 'hotels#show', as: 'hotels'
  get 'addhotels',to: 'hotels#new'
  post 'addhotels',to: 'hotels#create'
  get 'hotels/:id/edit', to: 'hotels#edit',as: 'edit_hotel'
  patch 'hotels/:id/edit',to: 'hotels#update'
  delete 'hotels/:id',to: 'hotels#destroy',as: 'delete_hotel'

  get 'listroomtypes' ,to: 'roomtypes#index'
  get 'roomtypes/:id',to: 'roomtypes#show', as: 'roomtypes'
  get 'addroomtypes',to: 'roomtypes#new'
  post 'addroomtypes',to: 'roomtypes#create'
  get 'roomtypes/:id/edit', to: 'roomtypes#edit',as: 'edit_roomtype'
  patch 'roomtypes/:id/edit',to: 'roomtypes#update'
  delete 'roomtypes/:id',to: 'roomtypes#destroy',as: 'delete_roomtype'

  get 'allotroom',to: 'rooms#index'
  get 'addguestandbooking' ,to: 'bookings#new'
  get 'addbookings' ,to: 'bookings#create'
  get '/bookings/:id',to: 'bookings#show',as: 'booking'
  get 'bills/new/:booking_id',to: 'bills#new',as:'new_booking_bill'
  post 'bills' ,to: 'bills#create',as: 'create_booking_bill'
  get '/bills/:id',to: 'bills#show',as: 'bill'
  get 'genbills',to: 'bills#payment'
  get 'feedbacks',to: 'feedbacks#new'
  post 'feedbacks',to: 'feedbacks#create'
  get 'addfeedbacks',to: 'feedbacks#create'
  post 'addfeedbacks',to: 'feedbacks#create'
  get 'thankyou',to: 'static_pages#thankyou'
  root 'static_pages#home'
  get 'static_pages/home'
  get 'static_pages/help'
  get 'signup' ,to: 'users#new'

  get 'login',to: 'sessions#new'
  post 'login',to: 'sessions#create'
  delete 'logout',to: 'sessions#destroy'


  resources :users
  get 'users/:id',to: 'users#show', as: 'usersshow'
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :booking
  validates :room_charge,:total_charge,:payment_date,:payment_mode,:transaction_id,:transaction_status,presence: true
  validates :room_charge,:total_charge, numericality: true
  validates :creditcard_number,:creditcard_expiry,presence: true
  before_create :calculate_charges,:generate_transaction_id,:set_default_transaction_status
  
  private
  def calculate_charges(booking)
    puts "@booking #{booking.inspect}"
    puts "checkin #{booking.checkin}"
    check_in_date=booking.checkin.to_date
    check_out_date=booking.checkout.to_date
    days=check_out_date-check_in_date
    hotel_id = booking.hotel_id
    roomtype_id = booking.room.roomtype_id
    puts "check in #{check_in_date}"
    puts "check out #{check_out_date}"
    puts "Days #{days}"
    puts "hotel id #{hotel_id}"
    puts "room type id #{roomtype_id}"
    if hotel_id ==1
      if roomtype_id==4
        self.room_charge=days*500
      elsif roomtype_id==5
        self.room_charge=days*400
      else 
        self.room_charge=600
      end
    elsif hotel_id ==2
      if roomtype_id==4
        self.room_charge=days*800
      elsif roomtype_id==5
        self.room_charge=days*700
      else 
        self.room_charge=days*900
      end
    elsif hotel_id ==3
      if roomtype_id==4
        self.room_charge=days*1100
      elsif roomtype_id==5
        self.room_charge=days*1000
      else 
        self.room_charge=days*1200
      end
    end
  self.roomservice_charge=days*100
  self.restaurant_charge=days*1000
  self.bar_charge=days*900
  self.misc_charge=0
  self.iflatecheckout_charge=0
  self.total_charge=self.room_charge+self.roomservice_charge+self.restaurant_charge+self.bar_charge+self.misc_charge+self.iflatecheckout_charge
  puts "Room charge #{self.room_charge}"
  puts "Room service charge #{self.roomservice_charge}"
  puts "Restaurant charge #{self.restaurant_charge}"
  puts "Bar charge #{self.bar_charge}"
  puts "Misc Charge #{self.misc_charge}"
  puts "If late checkout charge #{self.iflatecheckout_charge}"
  puts "Total charge #{self.total_charge}"
  end

  def generate_transaction_id
    self.transaction_id=SecureRandom.uuid
    puts "Txn Id #{self.transaction_id}"
  end
  
  def set_default_transaction_status
    self.transaction_status="paid"
    puts "Txn status #{self.transaction_status}"
  end
  
  public
  def calculate_values(booking)
    set_default_transaction_status
    generate_transaction_id
    calculate_charges(booking)
  end

end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
    def new
        @bill= Bill.new
        @booking = Booking.find(params[:booking_id])
        @bill.booking=@booking
        @bill.calculate_values(@booking)
    end
    
    def payment
        @bill=Bill.find(params[:id])
        if @bill
          flash[:success] = "Transaction Successful!"
        end
    end

    def show
        @bill= Bill.find(params[:id])
    end

    def create
        @booking = Booking.find(params[:booking_id])
        @bill = Bill.new(bill_params)
        @bill.inspect
        if @bill.save
            flash[:danger] = "Please complete payment!"
            redirect_to bill_path(@bill)
        else
          render :new
        end
    end

    private
    def bill_params
        params.require(:bill).permit(:room_charge,:roomservice_charge,:restaurant_charge,:bar_charge,:misc_charge,:iflatecheckout_charge,:total_charge,:payment_date,:payment_mode,:creditcard_number,:creditcard_expiry,:transaction_id,:transaction_status,:booking_id)
    end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/new.html.erb
<h1>Choose your payment mode:</h1>
<%= form_for @bill, url: create_booking_bill_path(booking_id: params[:booking_id]) do |f| %>
<%= csrf_meta_tags %>
  <div class="field">
    <%= f.label :payment_mode, "Payment Mode" %>
    <%= f.select :payment_mode, options_for_select(["cash", "card"]) %>
  </div>
  <% if @bill.payment_mode == "card" %>
    <div class="field">
      <%= f.label :creditcard_number, "Credit Card Number" %>
      <%= f.text_field :creditcard_number %>
    </div>
    <div class="field">
      <%= f.label :creditcard_expiry, "Credit Card Expiry" %>
      <%= f.date_select :creditcard_expiry %>
    </div>
  <% elsif @bill.payment_mode=="cash" %>
    <%= f.label :creditcard_number%>
    <%= f.text_field :creditcard_number,value: "NA", class: 'form-control' ,readonly: true %>
    
    <%= f.label :creditcard_expiry%>
    <%= f.text_field :creditcard_expiry,value: "NA" , class: 'form-control' ,readonly: true %>
  <% end %>
  <%= f.hidden_field :room_charge,value: @bill.room_charge%>
  <%= f.hidden_field :roomservice_charge,value: @bill.roomservice_charge%>
  <%= f.hidden_field :restaurant_charge,value: @bill.restaurant_charge%>
  <%= f.hidden_field :bar_charge,value: @bill.bar_charge%>
  <%= f.hidden_field :misc_charge,value: @bill.misc_charge%>
  <%= f.hidden_field :iflatecheckout_charge,value: @bill.iflatecheckout_charge%>
  <%= f.hidden_field :total_charge,value: @bill.total_charge%>
  <%= f.hidden_field :payment_date,value: DateTime.now%>
  <%= f.hidden_field :transaction_id,value: @bill.transaction_id%>
  <%= f.hidden_field :transaction_status,value: @bill.transaction_status%>
  <%= f.hidden_field :booking_id,value: @bill.booking_id%>
  <%= f.submit "Submit" %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token%>
<% end %>

app/views/bills/payment.html.erb
<h1>Thank You For Choosing Us !!</h1>
<br>
<h3>Transaction Id: <%=@bill.transaction_id%></h3>
<h3>Transaction Status: <%=@bill.transaction_status%></h3>

app/views/bills/show.html.erb
<h1>Bill is generated with Id- <%=@bill.id %></h1>
<p>Room Charge: <%=@bill.room_charge%></p>
<p>Room Service Charge: <%=@bill.roomservice_charge%></p>
<p>Restaurant Charge: <%=@bill.restaurant_charge%></p>
<p>Bar Charge: <%=@bill.bar_charge%></p>
<p>Miscellaneous Charge: <%=@bill.misc_charge%></p>
<p>Late Checkout(in case): <%=@bill.iflatecheckout_charge%></p>
<p>Total Charge: <%=@bill.total_charge%></p>
<p>Payment date:<%=@bill.payment_date%></p>
<p>Payment mode:<%=@bill.payment_mode%></p>
<h2>Please Pay-<%=@bill.total_charge%></h2>
<%= link_to "Pay Now",genbills_path(id: @bill.id)%>