config/routes.rb
Rails.application.routes.draw do 
  get 'rooms/index'
  get 'roomtypes/index'
  get 'listhotels', to: 'hotels#index'
  get 'hotels/:id',to: 'hotels#show', as: 'hotels'
  get 'addhotels',to: 'hotels#new'
  post 'addhotels',to: 'hotels#create'
  get 'hotels/:id/edit', to: 'hotels#edit',as: 'edit_hotel'
  patch 'hotels/:id/edit',to: 'hotels#update'
  delete 'hotels/:id',to: 'hotels#destroy',as: 'delete_hotel'

  get 'listroomtypes' ,to: 'roomtypes#index'
  get 'roomtypes/:id',to: 'roomtypes#show', as: 'roomtypes'
  get 'addroomtypes',to: 'roomtypes#new'
  post 'addroomtypes',to: 'roomtypes#create'
  get 'roomtypes/:id/edit', to: 'roomtypes#edit',as: 'edit_roomtype'
  patch 'roomtypes/:id/edit',to: 'roomtypes#update'
  delete 'roomtypes/:id',to: 'roomtypes#destroy',as: 'delete_roomtype'

  get 'allotroom',to: 'rooms#index'
  get 'addguestandbooking' ,to: 'bookings#new'
  get 'addbookings' ,to: 'bookings#create'
  get '/bookings/:id',to: 'bookings#show',as: 'booking'
  get 'bills/new/:booking_id',to: 'bills#new',as:'new_booking_bill'
  post 'bills' ,to: 'bills#create',as: 'create_booking_bill'
  get '/bills/:id',to: 'bills#show',as: 'bill'
  get 'genbills',to: 'bills#payment'
  get 'feedbacks',to: 'feedbacks#new'
  post 'feedbacks',to: 'feedbacks#create'
  get 'addfeedbacks',to: 'feedbacks#create'
  post 'addfeedbacks',to: 'feedbacks#create'
  get 'thankyou',to: 'static_pages#thankyou'
  root 'static_pages#home'
  get 'static_pages/home'
  get 'static_pages/help'
  get 'signup' ,to: 'users#new'

  get 'login',to: 'sessions#new'
  post 'login',to: 'sessions#create'
  delete 'logout',to: 'sessions#destroy'


  resources :users
  get 'users/:id',to: 'users#show', as: 'usersshow'
end

app/models/hotel.rb
class Hotel < ApplicationRecord
    validates :name,:address,:postalcode,:city,:country,:phonenumber,:starrating, presence: true
    belongs_to :owner
    has_many :employees
    has_many :rooms
    has_many :bookings
    has_many :guests
    validates :phonenumber,length: { maximum: 10 }
    #validates :starrating,maximum: 5.0
    #,comparison: { less_than_or_equal_to: 5.0 }
    validates :totalrooms,numericality: {only_integer: true}
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  include SessionsHelper
  def index
    @user=current_user
    @hotels=Hotel.all
  end
  def show
    @hotel= Hotel.find(params[:id])
  end

  def new
    @hotel = Hotel.new
  end

  def create
    @hotel = Hotel.new(hotel_params)
    if @hotel.save
      flash.now[:success] = "Hotel added to the list"
      redirect_to hotels_path(@hotel.id)
    else
      render 'new'
    end
  end
  
  def edit 
    @hotel = Hotel.find(params[:id])
  end

  def update 
    @hotel = Hotel.find(params[:id])
    if @hotel.update(hotel_params)
      flash.now[:success] = "Hotel is successfully updated!"
      redirect_to hotels_path(@hotel.id)
    else
      render 'edit'
    end
  end

  def destroy
    @hotel = Hotel.find(params[:id])
    @hotel.destroy
    flash.now[:success]= "Hotel deleted successfully!"
    redirect_to listhotels_path
  end

  private
  def hotel_params
    params.require(:hotel).permit(:name, :address, :postalcode,:city,:country,:totalrooms,:phonenumber,:starrating ,:owner_id)
  end
end

app/helpers/hotels_helper.rb
module HotelsHelper
    def current_hotel
        @current_hotel ||= Hotel.find_by(id: params[:hotel_id])
    end
end

app/views/hotels/edit.html.erb
<h1 class="text-center">Edit Hotel</h1>

<div class="row">
  <div class="mx-auto col-10 col-md-8 col-lg-6">
    <%= form_for @hotel, url: edit_hotel_path(@hotel),method: :patch do |f| %>
      <%= render 'shared/errors' %>

      <%= f.label :name %>
      <%= f.text_field :name ,class: 'form-control' %>

      <%= f.label :address %>
      <%= f.text_field :address ,class: 'form-control'%>

      <%= f.label :postalcode %>
      <%= f.text_field :postalcode ,class: 'form-control'%>

      <%= f.label :city %>
      <%= f.text_field :city ,class: 'form-control'%>

      <%= f.label :country %>
      <%= f.text_field :country ,class: 'form-control'%>

      <%= f.label :totalrooms%>
      <%= f.number_field :totalrooms,in: 1..1000 ,class: 'form-control'%>

      <%= f.label :phonenumber %>
      <%= f.text_field :phonenumber,class: 'form-control'%>
      
      <%= f.label :starrating %>
      <%= f.number_field :starrating,in: 0.5..5.0 ,step: 0.5,class: 'form-control'%>
      
      <%= f.label :owner_id %>
      <%= f.number_field :owner_id,in: 1..100 ,class: 'form-control'%>
      <br>
      <%= f.submit "Update Hotel", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/hotels/index.html.erb
<header class="header">
<h1>List Of Available Hotels</h1>
</header>
<ul>
  <% @hotels.each do |hotel|%>
    <li>
      <%= hotel.name %>
      <% if !admin? %>
      <%= link_to "View",hotels_path(hotel.id)%>
      <% end %>
      <% if admin? %>
      <%= link_to "View",hotels_path(hotel.id)%>
      <%= link_to "Modify",edit_hotel_path(hotel.id)%>
      <%= link_to "Delete",delete_hotel_path(hotel.id),method: :delete, data: {confirm: "Are You Sure?" }%>
      <% end %>
    </li>
  <% end %>
</ul>
<% if admin? %>
  <%= link_to "Add Hotel",addhotels_path%>
<% end %>
<br>
<%= link_to "Back", usersshow_path(@user.id)%>

app/views/hotels/new.html.erb
<h1 class="text-center">Add Hotel</h1>

<div class="row">
  <div class="mx-auto col-10 col-md-8 col-lg-6">
    <%= form_for @hotel, url: addhotels_path do |f| %>
      <%= render 'shared/errors' %>

      <%= f.label :name %>
      <%= f.text_field :name ,class: 'form-control' %>

      <%= f.label :address %>
      <%= f.text_field :address ,class: 'form-control'%>

      <%= f.label :postalcode %>
      <%= f.text_field :postalcode ,class: 'form-control'%>

      <%= f.label :city %>
      <%= f.text_field :city ,class: 'form-control'%>

      <%= f.label :country %>
      <%= f.text_field :country ,class: 'form-control'%>

      <%= f.label :totalrooms%>
      <%= f.number_field :totalrooms,in: 1..1000 ,class: 'form-control'%>

      <%= f.label :phonenumber %>
      <%= f.text_field :phonenumber,class: 'form-control'%>
      
      <%= f.label :starrating %>
      <%= f.number_field :starrating,in: 0.5..5.0 ,step: 0.5,class: 'form-control'%>
      
      <%= f.label :owner_id %>
      <%= f.number_field :owner_id,in: 1..100 ,class: 'form-control'%>
      <br>
      <%= f.submit "Add Hotel", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/hotels/show.html.erb
<header class="header">
<h1>Welcome to <%=@hotel.name%> </h1>
</header>
<h2>Details are as below:</h2>
<p>Name: <%=@hotel.name%></p>
<p>Address: <%=@hotel.address%></p>
<p>Postal Code: <%=@hotel.postalcode%></p>
<p>City: <%=@hotel.city%></p>
<p>Country: <%=@hotel.country%></p>
<p>Phone Number: <%=@hotel.phonenumber%></p>
<p>Rating: <%=@hotel.starrating%></p>
<%= link_to "Back", listhotels_path%>
<% if !admin? %>
<%= link_to "Select & Proceed", listroomtypes_path(hotel: @hotel)%>
<% end %>
<br>